apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: guardrails-detector-vibhorag101-suicide
  labels:
    opendatahub.io/dashboard: 'true'
  annotations:
    openshift.io/display-name: guardrails-detector-vibhorag101-suicide
    security.opendatahub.io/enable-auth: 'true'
    serving.knative.openshift.io/enablePassthrough: 'true'
    sidecar.istio.io/inject: 'true'
    sidecar.istio.io/rewriteAppHTTPProbers: 'true'
    serving.kserve.io/deploymentMode: RawDeployment
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: guardrails-detector-huggingface
      name: ''
      runtime: guardrails-detector-runtime-suicide
      storage:
        key: aws-connection-minio-data-connection-guardrails-suicide
        path: suicidality